services:
  - type: worker
    name: vertex-bot
    env: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
