services:
  - type: worker
    name: vertex-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
    pythonVersion: 3.10
